services:
  postgres:
    image: 'postgres:16.4'
    container_name: 'collation_db'
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - '5432:5432'

volumes:
  db-data: